sudo: false

language: groovy

jdk:
- oraclejdk7

branches:
  only:
    - travis

before_script:
   - chmod +x grailsw

script: ./grailsw clean && yes | ./grailsw refresh-dependencies && ./grailsw test-app