sudo: false

language: groovy

jdk:
  - openjdk7

before_script:
  - chmod +x grailsw
  - ./grailsw clean
  - GRAILS_VERSION=`grep '^\s*app.grails.version' ./application.properties | sed -e 's/^app.grails.version=//g' | tr -d "\r"`
  - echo "GRAILS_VERSION:$GRAILS_VERSION"
  - chmod +x "/home/travis/.grails/wrapper/$GRAILS_VERSION/grails-$GRAILS_VERSION/bin/grails"

script:  yes | ./grailsw refresh-dependencies && ./grailsw "test-app -echoOut -echoErr -coverage -xml"

after_success: ./grailsw coveralls

cache:
  directories:
  - $HOME/.m2
