sudo: false

language: groovy

jdk:
  - openjdk7

branches:
  only:
    - travis

before_script:
  - chmod +x grailsw

script: chmod +x /home/travis/.grails/wrapper/2.4.4/grails-2.4.4/bin/grails && ./grailsw clean && yes | ./grailsw refresh-dependencies && ./grailsw test-app