sudo: false

language: groovy

jdk:
  - openjdk7

branches:
  only:
    - travis

before_script:
  - chmod +x grailsw
  - ./grailsw clean
  - GRAILS_VERSION=`grep '^\s*grailsVersion' ./application.properties | sed -e 's/^app.grails.version=//g' | tr -d "\r"`
  - echo "GRAILS_VERSION:$GRAILS_VERSION"
  - chmod +x /home/travis/.grails/wrapper/2.4.4/grails-2.4.4/bin/grails

script:  yes | ./grailsw refresh-dependencies && ./grailsw 'test-app :cli -echoOut'